# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63\x61\x63he_service.proto\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\t\"\'\n\tCacheItem\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"$\n\x08NodeInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\",\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xae\x01\n\x0c\x43\x61\x63heService\x12$\n\x0cRegisterNode\x12\t.NodeInfo\x1a\t.Response\x12&\n\x0e\x44\x65registerNode\x12\t.NodeInfo\x1a\t.Response\x12\x17\n\x03Get\x12\x04.Key\x1a\n.CacheItem\x12\x1c\n\x03Put\x12\n.CacheItem\x1a\t.Response\x12\x19\n\x06Remove\x12\x04.Key\x1a\t.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cache_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_KEY']._serialized_start=23
  _globals['_KEY']._serialized_end=41
  _globals['_CACHEITEM']._serialized_start=43
  _globals['_CACHEITEM']._serialized_end=82
  _globals['_NODEINFO']._serialized_start=84
  _globals['_NODEINFO']._serialized_end=120
  _globals['_RESPONSE']._serialized_start=122
  _globals['_RESPONSE']._serialized_end=166
  _globals['_CACHESERVICE']._serialized_start=169
  _globals['_CACHESERVICE']._serialized_end=343
# @@protoc_insertion_point(module_scope)
